apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.applicationName }}-supergraph
  namespace: {{ .Release.Namespace }}
data:
  supergraph.graphql: |
    schema
      @link(url: "https://specs.apollo.dev/link/v1.0")
      @link(url: "https://specs.apollo.dev/join/v0.3", for: EXECUTION)
    {
      query: Query
    }
    
    directive @join__enumValue(graph: join__Graph!) repeatable on ENUM_VALUE
    
    directive @join__field(graph: join__Graph, requires: join__FieldSet, provides: join__FieldSet, type: String, external: Boolean, override: String, usedOverridden: Boolean) repeatable on FIELD_DEFINITION | INPUT_FIELD_DEFINITION
    
    directive @join__graph(name: String!, url: String!) on ENUM_VALUE
    
    directive @join__implements(graph: join__Graph!, interface: String!) repeatable on OBJECT | INTERFACE
    
    directive @join__type(graph: join__Graph!, key: join__FieldSet, extension: Boolean! = false, resolvable: Boolean! = true, isInterfaceObject: Boolean! = false) repeatable on OBJECT | INTERFACE | UNION | ENUM | INPUT_OBJECT | SCALAR
    
    directive @join__unionMember(graph: join__Graph!, member: String!) repeatable on UNION
    
    directive @link(url: String, as: String, for: link__Purpose, import: [link__Import]) repeatable on SCHEMA
    
    type Hero
      @join__type(graph: HEROES, key: "id")
    {
      id: ID!
      name: String!
      power: String!
    }
    
    scalar join__FieldSet
    
    enum join__Graph {
      HEROES @join__graph(name: "heroes", url: "http://heroes-service-service.apollo.svc.cluster.local:4001/")
      MISSIONS @join__graph(name: "missions", url: "http://missions-service-service.apollo.svc.cluster.local:4002/")
    }
    
    scalar link__Import
    
    enum link__Purpose {
      """
      `SECURITY` features provide metadata necessary to securely resolve fields.
      """
      SECURITY
    
      """
      `EXECUTION` features provide metadata necessary for operation execution.
      """
      EXECUTION
    }
    
    type Mission
      @join__type(graph: MISSIONS, key: "id")
    {
      id: ID!
      name: String!
      difficulty: String!
    }
    
    type Query
      @join__type(graph: HEROES)
      @join__type(graph: MISSIONS)
    {
      heroes: [Hero!]! @join__field(graph: HEROES)
      missions: [Mission!]! @join__field(graph: MISSIONS)
    }
